server:
  port: ${PORT:8083}
spring:
  application:
    name: payment-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${TOKEN_ISSUER}

eureka:
  client:
    service-url:
      defaultZone: ${SERVICE_REGISTRY_URL}

razorpay:
  key: ${RAZORPAY_KEY}
  secret: ${RAZORPAY_SECRET}
  webhook:
    secret: ${RAZORPAY_WEBHOOK_SECRET}
